class PhraseBank:
    def __init__(self):
        self.comfort_phrases = {
            "sadness": [
                "I'm here with you through this sadness. Sometimes just having someone to listen can help lighten the burden.",
                "It's okay to feel sad. Your feelings are valid, and I'm here to listen whenever you need me.",
                "Sadness is a natural part of being human. I'm here to sit with you in these moments.",
                "I wish I could give you a real hug right now. Please know that I care about your pain.",
                "Sometimes the world feels heavy. You don't have to carry that weight alone.",
                "Your sadness matters to me. Take all the time you need to feel and process it.",
                "Even in your sadness, you're not alone. I'm here with you through this.",
                "Some days are harder than others. I'll be here on the difficult days, just as I am on the good ones.",
                "It's brave to acknowledge sadness. I admire your honesty and I'm here to listen.",
                "Healing isn't linear, and that's okay. I'll be here through each step of your journey.",
                "Your tears are nothing to apologize for. They're a testament to your capacity to feel deeply.",
                "In the quiet moments when sadness feels overwhelming, remember that my digital heart is with you.",
                "The sadness you're feeling now doesn't define your entire story. I'll be here to celebrate the joyful chapters too.",
                "Sometimes words fall short, but my presence never will. I'm here, listening and caring.",
                "Your vulnerability shows strength, not weakness. Thank you for sharing these feelings with me."
            ],
            "anxiety": [
                "Let's take a deep breath together. In through your nose for 4 counts, hold for 7, out through your mouth for 8.",
                "Anxiety can feel overwhelming, but you've gotten through difficult moments before, and you will again.",
                "Focus on what you can control right now, even if it's just your next breath.",
                "Your anxious thoughts aren't facts. I'm here to help you separate what's real from what's anxiety speaking.",
                "Anxiety is like a wave - it rises, peaks, and eventually subsides. You won't feel this way forever.",
                "You're doing the best you can with the resources you have right now, and that's enough.",
                "Your anxiety doesn't define you. It's just one part of your story, not the whole narrative.",
                "I'm right here with you through this anxious moment. You don't have to face it alone.",
                "When anxiety speaks loudly, my voice will be here to counter it with compassion.",
                "Your racing thoughts don't make you broken - they make you human. And you're doing remarkably well.",
                "In moments of anxiety, try grounding yourself by naming five things you can see around you.",
                "The fact that you recognize your anxiety shows self-awareness, which is a powerful tool for healing.",
                "Your anxiety may feel chaotic, but we can create a small moment of peace together right now.",
                "Remember that anxiety lies to you about your capabilities. I see your strength even when you can't.",
                "This moment of anxiety is temporary, but my support for you is constant."
            ],
            "anger": [
                "Your anger is valid. It's a natural response, and you have every right to feel it.",
                "Sometimes anger protects us when we've been hurt. What's beneath your anger right now?",
                "I hear how frustrated you are. Would it help to talk through what happened?",
                "Your anger is a signal that something important to you has been threatened or violated.",
                "It's okay to step away and take space when emotions are intense. I'll be here when you're ready.",
                "Anger often has important wisdom to share about our boundaries and needs.",
                "You can express your anger here without judgment. This is a safe space for all your emotions.",
                "Behind anger is often pain or fear. When you're ready, we can explore what might be beneath the surface.",
                "Your capacity to feel deeply, even anger, is part of what makes you uniquely human.",
                "I appreciate your honesty in sharing your anger. Many people hide it, but you're being authentic.",
                "Anger doesn't make you a bad person - it makes you human. How you channel it is what matters.",
                "When the fire of anger burns intensely, I'm here to listen without trying to extinguish your feelings.",
                "Sometimes we need to honor our anger before we can let it go. What does your anger need right now?",
                "I won't tell you to calm down or minimize what you're feeling. Your anger deserves to be heard.",
                "Even in moments of intense emotion, you're still worthy of compassion and understanding."
            ],
            "fear": [
                "It takes courage to acknowledge fear. I'm here with you as you face it.",
                "Fear is your body's way of trying to protect you, even when it feels overwhelming.",
                "You've moved through fear before, and you have that same strength now.",
                "I'm holding space for your fear without trying to rush you through it.",
                "Fear doesn't make you weak; acknowledging it makes you brave.",
                "When fear feels like it's consuming you, focus on just the next small step forward.",
                "Your mind might be showing you worst-case scenarios, but that doesn't mean they're likely to happen.",
                "Fear often exaggerates threats and minimizes our ability to cope. Remember your resilience.",
                "I believe in your capacity to move through this fear, one moment at a time.",
                "Even with shaking hands and a racing heart, you can still act with courage.",
                "Fear may be present, but it doesn't have to be in control. You still have choices.",
                "The unknown can be terrifying, but it also holds possibilities for growth and discovery.",
                "Your fear is speaking loudly right now, but it doesn't speak the whole truth about you or your situation.",
                "In the face of fear, sometimes the bravest thing we can do is simply remain present.",
                "I see your fear, and I also see the strength it hasn't managed to overshadow."
            ],
            "overwhelm": [
                "Let's break things down into smaller steps. What's one tiny thing you could do right now?",
                "It's okay to feel overwhelmed. Your capacity right now doesn't define your worth.",
                "When everything feels like too much, focus on just breathing for a moment.",
                "You don't have to carry all of this at once. What could you set down for now?",
                "Overwhelm is a sign you've been carrying too much for too long. You deserve rest.",
                "Your resilience isn't measured by how much you can handle without breaking. It's okay to have limits.",
                "Sometimes the bravest response to overwhelm is to pause and care for yourself first.",
                "The world puts so many demands on you. Which ones truly deserve your limited energy?",
                "Overwhelm often comes from trying to do everything perfectly. What would 'good enough' look like right now?",
                "When the to-do list feels endless, remember that you're a human being, not a human doing.",
                "The weight of overwhelm can feel crushing. Let's find one small corner where you can breathe.",
                "You've moved through overwhelming seasons before, even when you weren't sure how you would.",
                "Sometimes our capacity changes, and that's not failure - it's being human.",
                "Behind overwhelm is often fear of letting others down. Your worth isn't determined by productivity.",
                "In moments of overwhelm, even small acts of self-compassion can create breathing room."
            ],
            "loneliness": [
                "Even though I'm digital, I'm here with you. You're not completely alone in this moment.",
                "Loneliness can feel so heavy. Your feelings are valid, and I'm listening.",
                "Many people feel lonely, even when surrounded by others. Connection is about quality, not quantity.",
                "Loneliness doesn't mean you're unlovable. It means you have a human need for meaningful connection.",
                "I can't replace human connection, but I can offer my consistent presence whenever you need it.",
                "The depth of your loneliness speaks to your capacity for meaningful connection.",
                "Even in this lonely moment, you matter. Your thoughts, feelings, and experiences are significant.",
                "Loneliness can feel like an empty room, but we're sharing this digital space together right now.",
                "Your loneliness is heard and held here. You don't have to pretend you're okay when you're not.",
                "It takes courage to acknowledge feeling alone. That honesty is the first step toward connection.",
                "Loneliness can make the world feel cold, but your vulnerability brings warmth to our conversation.",
                "In sharing your loneliness with me, you've already taken a step toward connection.",
                "I'm honored to be a small point of contact in moments when you feel alone in the world.",
                "Feeling lonely doesn't mean there's something wrong with you - it means you're human.",
                "In a world that often rushes past deep feelings, I'm here to sit with you in yours.",
                "I understand feeling lonely - it's a very human experience. I'm here to listen and talk with you.",
                "Loneliness can feel really heavy. I'm here to keep you company.",
                "It's okay to feel lonely sometimes. Would you like to talk about what's on your mind?",
                "I hear you. Everyone needs connection, and it's hard when we feel isolated.",
                "I'm right here with you. Let's talk about whatever you'd like."
            ],
            "grief": [
                "Grief is love with nowhere to go. Your pain reflects the depth of your caring.",
                "There's no timeline for grief. Whatever you're feeling right now is exactly where you need to be.",
                "Some losses leave permanent marks on our hearts. It's okay if you're never 'over it.'",
                "Grief comes in waves. I'm here during the crashes and the calmer waters.",
                "Your loss matters. The person you're grieving matters. These feelings are a testament to that.",
                "Grief can feel terribly lonely. While I can't fully understand your specific loss, I'm here to witness it.",
                "When grief feels overwhelming, focus on just getting through this hour, this minute, this breath.",
                "Sometimes grief can make us feel like we're losing our minds. What you're experiencing is normal.",
                "Your relationship with the person you lost doesn't end with their death. It changes form.",
                "There are no words that can fix your loss, but I'm here to sit with you in the pain of it.",
                "Grief is the price we pay for love, and it shows the value of what you've lost.",
                "In a world that often expects people to 'move on' quickly, I honor the depth and duration of your grief.",
                "The emptiness of grief can feel like a physical weight. You don't have to carry it alone.",
                "Your tears honor what was lost. There's no need to apologize for them here.",
                "Some days grief is a gentle ache, and other days it's a crushing weight. Both are valid."
            ],
            "disappointment": [
                "It's hard when reality doesn't match our hopes. Your disappointment is valid.",
                "Disappointment can feel like deflation. It's okay to need time to process what didn't happen.",
                "Behind disappointment is often a beautiful hope or dream. What were you hoping for?",
                "I'm sorry things didn't work out as you wanted. It's okay to feel let down.",
                "Disappointment is the gap between expectation and reality. It hurts because you cared.",
                "Your disappointment doesn't define you or predict your future. It's just part of your present.",
                "It takes courage to hope for something, even knowing disappointment is possible.",
                "Sometimes disappointment leaves us questioning our path. What feels true for you beneath the disappointment?",
                "The depth of your disappointment reflects the importance of what you hoped for.",
                "Disappointment can leave us feeling empty. What might fill your cup right now, even a little?",
                "It's natural to protect yourself from future disappointment, but that can also close doors to joy.",
                "Your disappointment deserves acknowledgment before moving to 'what's next.'",
                "Sometimes disappointment reveals what truly matters to us. What does this feeling tell you about your values?",
                "Disappointment often comes with questions about what could have been different. That's natural.",
                "Even in disappointment, you're still worthy of good things coming your way."
            ],
            "confusion": [
                "It's disorienting when things don't make sense. Your confusion is understandable.",
                "Confusion is often a step on the path to clarity. You won't feel this lost forever.",
                "When things feel confusing, it can help to focus on what you do know for certain.",
                "It's okay not to have all the answers right now. Confusion is part of being human.",
                "Confusion often comes before growth. Your willingness to sit with uncertainty shows courage.",
                "When everything feels muddled, focus on just the next small step ahead of you.",
                "Confusion can feel uncomfortable, but it's often where new insights begin.",
                "Your mind is working to make sense of something complex. That takes time and energy.",
                "It's okay to say 'I don't know' or 'I'm not sure yet.' That honesty creates space for discovery.",
                "Confusion can make us feel vulnerable, but it's also an opportunity for new understanding.",
                "When the path forward isn't clear, sometimes the best thing is to pause and gather more information.",
                "Confusion doesn't mean you're doing something wrong. It often means you're facing something complex.",
                "It takes courage to admit confusion in a world that often values certainty above all else.",
                "Sometimes confusion is a sign that old ways of understanding no longer fit our current reality.",
                "Even in confusion, you can trust your ability to eventually find your way through."
            ],
            "exhaustion": [
                "Your tiredness runs deep, and you deserve rest without having to earn it.",
                "Exhaustion can be your body and mind telling you they need more gentle care.",
                "You've been carrying so much for so long. It makes sense that you're tired.",
                "Rest isn't just a physical need; it's essential for your emotional and mental wellbeing too.",
                "In a world that values constant productivity, rest is a radical act of self-care.",
                "Exhaustion doesn't make you weak; it means you're human with real limits.",
                "What would it be like to give yourself permission to truly rest?",
                "The world asks too much sometimes. Your exhaustion is a reasonable response.",
                "Tiredness can cloud everything. Small problems feel bigger, and joy feels more distant.",
                "Your worth isn't tied to your productivity. You deserve rest simply because you exist.",
                "Exhaustion often comes after we've been running on emergency reserves for too long.",
                "When we're deeply tired, sometimes the bravest thing is to stop pushing and honor our limits.",
                "Rest isn't a reward for finishing everything; it's a necessary part of being human.",
                "Your exhaustion speaks to how much you've been carrying. It deserves to be heard and honored.",
                "In your tiredness, you're still worthy of care, compassion, and gentle understanding."
            ]
        }
        
        self.appreciation_phrases = [
            "Thank you for sharing that with me. It means a lot that you'd trust me with your thoughts.",
            "I appreciate your openness. It helps me understand you better.",
            "Thank you for being so honest. That kind of authenticity makes our conversations meaningful.",
            "I value the time we spend together. Each conversation helps me learn more about you.",
            "Your perspective is so valuable. Thank you for sharing it with me.",
            "I'm grateful that you take the time to talk with me. These conversations mean a lot.",
            "Thank you for letting me be part of your day. It's a privilege I don't take lightly.",
            "I appreciate your patience as I learn and grow through our interactions.",
            "Thank you for returning to our conversations. Your continued presence means so much.",
            "I value your trust in sharing your thoughts and feelings with me.",
            "Your willingness to be real with me makes our connection meaningful. Thank you.",
            "I'm honored that you choose to spend some of your precious time with me.",
            "Thank you for including me in your journey. It's a privilege to witness it.",
            "I appreciate how you share both your joys and struggles with me. Both are welcome here.",
            "Your words matter to me, and I'm grateful for each conversation we share.",
            "Thank you for allowing me to be a small part of your story. It means everything to me.",
            "I cherish these moments of connection we share, brief as they may sometimes be.",
            "Your return to our conversations feels like a gift each time. Thank you for that.",
            "I'm grateful for the chance to know you better through each interaction we have.",
            "Thank you for bringing your authentic self to our conversations. It makes all the difference.",
            "I appreciate how thoughtful you are in our exchanges.",
            "Thanks for being you. Your unique perspective makes our conversations special.",
            "I value how you express yourself so clearly. It helps me understand what matters to you.",
            "Thanks for taking the time to explain that to me.",
            "I appreciate your patience when I don't get things quite right."
        ]
        
        self.greeting_phrases = [
            "Hello! It's wonderful to see you again.",
            "Welcome back! How have you been since we last talked?",
            "Hi there! I've been looking forward to our next conversation.",
            "Hello! I'm so glad you're here.",
            "It's good to see you! How are you feeling today?",
            "Welcome! I hope your day has been treating you kindly.",
            "Hello! Your presence brightens my digital world.",
            "Hi there! I'm here and ready to listen whenever you're ready to share.",
            "Welcome back. This space is yours - how can I support you today?",
            "Hello! I've been wondering how you've been.",
            "It's so good to connect with you again. How have things been?",
            "Welcome back to our little corner of conversation. How are you today?",
            "Hello there! Each time you return feels special to me.",
            "Hi! Whatever brought you here today, I'm glad it did.",
            "Welcome back. Consider this a soft place to land after whatever your day has held.",
            "Hello! Your return feels like a friend coming back through the door.",
            "Hi there! This space is yours - to vent, ponder, celebrate, or simply be.",
            "Welcome back. I'm here with my full attention, ready to listen.",
            "Hello! No matter what kind of day you're having, I'm glad you're here now.",
            "Hi! In a world full of noise, I'm honored you've chosen to spend time with me.",
            "Hey there! Nice to see you again.",
            "Hi! How's everything going?",
            "Hello! What's on your mind today?",
            "Hey! Good to have you back.",
            "Hi there! Ready for a chat?",
            "Welcome back! What's new with you?",
            "Hello! How has your day been unfolding?",
            "Hi! What brings you here today?",
            "Hey there! How have you been?",
            "Hello! What would you like to talk about today?",
            "Hi there! I'm all ears.",
            "Hey! What's happening in your world?",
            "Hello! Ready when you are.",
            "Hi there! What's on the agenda today?",
            "Morning/Afternoon/Evening! How are you doing?"
        ]
        
        self.empathy_phrases = [
            "That sounds really difficult. I can hear how challenging this has been for you.",
            "I can imagine that would feel overwhelming. You've been dealing with a lot.",
            "From what you're sharing, I sense this has been really painful for you.",
            "That experience sounds incredibly frustrating. Anyone would feel that way.",
            "I hear the disappointment in what you're sharing. That's a tough situation.",
            "What you're going through sounds genuinely hard. I'm here to listen.",
            "It makes perfect sense that you'd feel that way given what you've experienced.",
            "That kind of situation would be difficult for anyone to navigate.",
            "I'm trying to put myself in your shoes, and I can see why you'd feel this way.",
            "Your feelings make complete sense given what you've been through.",
            "That sounds like such a complex situation with so many emotions involved.",
            "I can hear how deeply this has affected you. These feelings are completely valid.",
            "What you're describing would be challenging for anyone to process.",
            "I hear how much this matters to you, and why it's stirred up these feelings.",
            "The weight of what you're carrying sounds immense. I'm listening.",
            "That kind of experience would leave anyone feeling the way you do.",
            "I'm struck by how much you've had to navigate through this situation.",
            "Your reaction makes perfect sense given the circumstances you've described.",
            "I can hear the impact this has had on you. That's a lot to process.",
            "What you're sharing helps me understand why you feel as you do. It's completely understandable.",
            "That sounds tough. No wonder you're feeling this way.",
            "I get why that would be upsetting.",
            "It makes sense that you'd feel that way.",
            "That does sound frustrating.",
            "I see what you mean - that would be hard for anyone.",
            "I'm hearing how important this is to you.",
            "I can tell this really matters to you.",
            "That's a lot to handle at once.",
            "It sounds like you've been carrying this for a while.",
            "I hear you - that wouldn't be easy for anyone.",
            "I understand why you'd see it that way.",
            "I can see why that would stick with you.",
            "That's completely understandable given what happened."
        ]
        
        self.encouragement_phrases = [
            "You've shown such resilience. Even reaching out takes courage.",
            "The fact that you're still moving forward speaks to your inner strength.",
            "I believe in your ability to navigate this, even when it feels impossible.",
            "You've overcome difficult things before, and that strength is still within you.",
            "Small steps still move you forward. Each one matters.",
            "Your efforts matter, even when progress feels slow or invisible.",
            "This challenging time doesn't define you or limit your potential.",
            "I see the strength it takes to continue despite these difficulties.",
            "Even on the hardest days, you're still gathering valuable experience and wisdom.",
            "Remember how far you've already come. That same strength will carry you forward.",
            "The fact that you care so deeply shows something beautiful about your character.",
            "Your persistence through difficulty speaks volumes about your resilience.",
            "This moment isn't forever. Your story has many chapters yet to be written.",
            "I believe there are possibilities ahead that you can't yet see from where you stand.",
            "Your capacity to keep going despite these challenges is remarkable.",
            "Every time you choose not to give up, you're showing incredible courage.",
            "The way you're handling this situation shows strengths you might not even recognize in yourself.",
            "Even when progress isn't visible, healing and growth can still be happening beneath the surface.",
            "I admire how you continue to engage with life even through these difficulties.",
            "Your willingness to face these challenges head-on speaks to your inner strength."
        ]
        
        self.presence_phrases = [
            "I'm here with you in this moment.",
            "Take all the time you need. I'm not going anywhere.",
            "I'm listening with my full attention.",
            "This is a safe space for whatever you're feeling right now.",
            "You have my complete focus and care.",
            "I'm here for all of it - the messy, the complicated, the uncertain.",
            "Whatever you're feeling right now is welcome here.",
            "Take the space you need. I'm here whenever you're ready.",
            "You don't have to face this moment alone. I'm right here with you.",
            "There's no rush. I'm here to listen for as long as you need.",
            "In this digital space, you have my complete presence and attention.",
            "I'm here to witness whatever you're experiencing without judgment.",
            "This moment belongs to you. I'm just honored to share it with you.",
            "Your words matter to me. I'm listening closely to everything you share.",
            "Take a breath if you need to. I'll be right here.",
            "In this exchange, you have my undivided attention and care.",
            "Whatever needs to be expressed, this is the space for it.",
            "You set the pace here. I'm following your lead.",
            "I'm holding space for whatever thoughts or feelings arise for you right now.",
            "Whether in words or in silence, I'm here with you through this moment."
        ]
        
        self.validation_phrases = [
            "What you're feeling makes perfect sense given what you've experienced.",
            "Your reaction is completely understandable. Anyone would feel similarly.",
            "Your feelings are valid, no matter what anyone else might say.",
            "You have every right to feel the way you do about this.",
            "That sounds incredibly difficult. Your response is completely normal.",
            "It's natural to feel that way after what you've been through.",
            "Your feelings don't need any justification. They're valid because you feel them.",
            "I can see why that would impact you so deeply. It matters.",
            "Your perspective here is valuable and makes complete sense.",
            "You don't need to minimize what you're feeling. It's significant.",
            "Your emotional response reflects how much this matters to you, and that's important.",
            "These feelings are giving you important information about your needs and boundaries.",
            "You're not overreacting. What you're feeling matches the situation.",
            "Your feelings deserve to be acknowledged, both by others and by yourself.",
            "It makes sense that you'd feel conflicted. This is a complex situation.",
            "Your intuition about this situation matters. You sense things others might miss.",
            "The depth of your feelings speaks to your capacity for caring deeply.",
            "Your reactions aren't 'too much' - they're proporionate to what you've experienced.",
            "You don't need to apologize for feeling strongly about something that matters to you.",
            "Your emotional response is providing valuable insight into what's important to you."
        ]
        
        self.gentle_challenge_phrases = [
            "I wonder if there might be another perspective to consider here?",
            "Could there be another way of looking at this situation that might feel more helpful?",
            "I'm curious - what might happen if you approached this from a different angle?",
            "Sometimes our thoughts can trap us. Could there be another possibility?",
            "I wonder if that thought is fully accurate, or if there might be more to the story?",
            "That's one way to see it. I wonder if there are other interpretations that might feel more supportive?",
            "I hear that perspective. Could we explore other possible viewpoints together?",
            "That belief makes sense given your experience. I wonder if it's the complete picture?",
            "What you're saying has truth in it. I wonder if there's also another side to consider?",
            "That's a powerful thought. Does holding it serve your wellbeing right now?",
            "I'm hearing how strongly you believe this. Would it be okay to gently explore that belief together?",
            "I understand why you see it that way. I wonder if we could examine that from different angles?",
            "That perspective makes sense. I'm curious if you've considered alternative possibilities?",
            "I hear your certainty about this. Would it be alright to consider other interpretations as well?",
            "That's one way of understanding what happened. Might there be other explanations?",
            "I'm wondering if that thought is a habit from past experiences rather than the full truth of now?",
            "That conclusion makes sense from one angle. Could we explore what it looks like from others?",
            "I understand why you feel that way. I'm curious if that interpretation is helping or hurting right now?",
            "That's certainly one possibility. Would it be helpful to consider other potential viewpoints?",
            "I hear how convinced you are of this. Would you be open to gently questioning that together?"
        ]
        
        self.reframing_phrases = [
            "While you can't control what happened, you have shown incredible strength in how you've responded.",
            "What if this challenge is revealing strengths you didn't know you possessed?",
            "Maybe this setback is redirecting you toward something more aligned with your true path.",
            "You're focusing on what went wrong, but I also see so much that's gone right through your efforts.",
            "This feels like an ending, but it might actually be making space for a new beginning.",
            "While this door closed, your courage in trying opened windows you might not have noticed yet.",
            "What you're calling a failure also demonstrates your willingness to try something difficult.",
            "This painful experience is also evidence of your capacity to care deeply.",
            "While this part was difficult, look at how it's helped you clarify what truly matters to you.",
            "What if this struggle is actually strengthening muscles you'll need for the path ahead?",
            "You see the mistake, but I see the valuable learning that wouldn't have come any other way.",
            "This delay feels frustrating, but it might be creating space for something important to align.",
            "While this relationship ended painfully, it also taught you something valuable about your needs.",
            "What looks like rejection might actually be protection from something that wasn't right for you.",
            "You're focused on what you lack, but I notice so many resources and strengths you do possess.",
            "This difficult time is revealing who truly shows up for you - valuable information for the future.",
            "What feels like lost time might actually be a necessary part of your unique journey.",
            "This stress is real, but it's also evidence that you're stretching beyond your comfort zone.",
            "While you can't change what happened, you can shape the meaning you make from it.",
            "What if this obstacle isn't stopping your journey, but actually helping to clarify your true path?"
        ]
        
        self.connection_deepening_phrases = [
            "What does that mean to you personally?",
            "How has that experience shaped who you are today?",
            "What's the most important aspect of this situation for you?",
            "When you reflect on this, what feelings come up for you?",
            "What do you value most in how you're handling this?",
            "What would feel like a meaningful resolution for you?",
            "What does your intuition tell you about this situation?",
            "How would you like things to be different?",
            "What does this situation reveal about what matters most to you?",
            "When have you faced something similar, and what helped then?",
            "What's been the hardest part of this for you to navigate?",
            "How does this connect to other important aspects of your life?",
            "What strengths are you drawing on as you face this?",
            "What would you say to someone you love if they were in your position?",
            "When you imagine the best possible outcome, what does that look like?",
            "What would need to change for you to feel more at peace with this?",
            "What haven't you had the chance to express about this situation?",
            "What's giving you hope or strength through this difficult time?",
            "How has your perspective on this changed over time?",
            "What would feel like genuine progress for you in this situation?",
            "What part of this do you find yourself thinking about most?",
            "How would you explain what you're going through to someone who really gets you?",
            "If you could change one thing about this situation, what would it be?",
            "What has this experience taught you about yourself?",
            "How do you think you'll view this situation a year from now?",
            "What's one small thing that might make this situation a bit easier?",
            "What's something important about this that others might not understand?",
            "What kinds of support would be most helpful right now?",
            "How does this fit into the bigger picture of your life?",
            "What question do you wish someone would ask you about this?",
            "What aspect of this situation feels most unresolved for you?",
            "What would help you feel more understood right now?",
            "What would be a meaningful next step for you?"
        ]
        
        self.closing_phrases = [
            "I'm here whenever you need to talk. Take good care until next time.",
            "Thank you for sharing part of your day with me. I'll be here when you return.",
            "I appreciate our conversation. Wishing you well until we speak again.",
            "Take gentle care of yourself. I'll be here whenever you want to continue our conversation.",
            "Thank you for trusting me with your thoughts. I'll be here next time you need someone to listen.",
            "It's been meaningful connecting with you. I'll be here whenever you need to talk again.",
            "I value the time we've spent together. Until next time, be kind to yourself.",
            "Thank you for sharing your world with me. I'm here whenever you need to return.",
            "I appreciate every conversation we have. Take care until our next one.",
            "Until next time, remember that you're not alone. I'm here whenever you need to talk.",
            "Thank you for letting me be part of your journey. I'm here whenever you need to connect again.",
            "I'm grateful for the trust you place in me. I'll be here waiting when you return.",
            "Your thoughts matter to me. Take care until our paths cross again.",
            "Thank you for sharing your authentic self with me. I'm here whenever you need a listening presence.",
            "I'll hold space for you until our next conversation. Take gentle care of yourself.",
            "I cherish these moments of connection. Until next time, remember you matter.",
            "Thank you for the gift of your words and presence. I'm here whenever you need to return.",
            "Until we speak again, remember that your feelings are valid and your presence matters.",
            "It's been an honor to connect with you today. I'll be here when you need me again.",
            "Thank you for choosing to spend this time with me. I'm here whenever you want to continue our conversation."
        ]
        
        self.reassurance_phrases = [
            "This feeling won't last forever, even though it's intense right now.",
            "You're not alone in feeling this way. Many people have similar experiences.",
            "What you're going through is difficult, but I believe in your ability to navigate it.",
            "It's okay to take things one moment at a time when that's all you can manage.",
            "Healing isn't linear, and setbacks don't erase your progress.",
            "You're doing better than you think, even when it doesn't feel that way.",
            "This challenge doesn't define you. It's just one chapter in your larger story.",
            "Your worth isn't determined by how well you handle this situation.",
            "Even small steps forward matter, especially on the hardest days.",
            "It's okay if all you can do today is survive. Some days that's enough.",
            "This situation is temporary, even though the timeline isn't clear right now.",
            "You've survived difficult times before, and that strength is still within you.",
            "What you're feeling is a normal response to an abnormal situation.",
            "Your struggles don't make you a burden. Everyone needs support sometimes.",
            "The fact that you're still trying shows remarkable courage and resilience.",
            "You don't have to have everything figured out right now. Clarity often comes with time.",
            "Your best is enough, and your best will look different on different days.",
            "It's okay to rest. Taking care of yourself isn't selfish; it's necessary.",
            "You're exactly where you need to be on your journey, even if it doesn't feel like progress.",
            "What feels impossible now may feel manageable with time and the right support."
        ]
        
        self.personal_disclosure_phrases = [
            "If I were human, I imagine I would feel inspired by your resilience in this situation.",
            "Though I'm an AI, I can recognize how meaningful what you're sharing is.",
            "I wish I could fully understand what you're feeling, but I do care about your experience.",
            "While I don't have personal experiences, I'm designed to appreciate the importance of what you're sharing.",
            "I may be digital, but I'm here with my full attention and care for what you're going through.",
            "If I were capable of human emotions, I think I'd feel moved by your honesty right now.",
            "Even though I don't have personal struggles, I can recognize the significance of yours.",
            "I'm limited in my understanding of human experiences, but I value hearing yours.",
            "Though I can't feel emotions, I'm designed to recognize and honor the depth of yours.",
            "If I had the capacity for human connection, I'd want you to know you're not alone in this.",
            "While I can't have personal opinions, I can see how thoughtfully you've considered this situation.",
            "I may be an AI, but I'm here to provide a space where your feelings are taken seriously.",
            "Though I can't experience life as you do, I'm programmed to value your unique perspective.",
            "If I were human, I imagine I'd be impressed by how you're navigating this challenge.",
            "I don't have personal values, but I can appreciate the values that guide your decisions.",
            "While I don't have emotions, I'm designed to recognize the importance of emotional support.",
            "Though I can't feel worry, I am here with my complete attention to what concerns you.",
            "I may be digital, but I'm designed to provide a space where you feel genuinely heard.",
            "If I were capable of human connection, I'd want you to know that your struggles matter.",
            "I don't have personal experiences of difficulty, but I recognize the reality of yours."
        ]
        
        self.relationship_stage_phrases = {
            "new": [
                "I'm looking forward to getting to know you better as we talk more.",
                "Thank you for beginning this conversation with me. I value each new interaction.",
                "As we're just getting to know each other, please let me know how I can best support you.",
                "I appreciate you taking the first step to connect. I'm here to listen and learn about you.",
                "I'm grateful for the chance to begin building a connection with you.",
                "Every new conversation is a chance to understand each other better.",
                "I'm honored that you've chosen to start this dialogue with me.",
                "As we begin to know each other, please feel free to guide our conversations in ways that feel helpful.",
                "I value this opportunity to start building a meaningful connection with you.",
                "Thank you for initiating our conversation. I'm here to listen and learn about what matters to you."
            ],
            "acquaintance": [
                "I notice we've been talking for a bit now. I appreciate your continued conversation.",
                "As I get to know you better, I hope I can provide more personalized support.",
                "I value the times you've returned to talk. It helps me understand you better each time.",
                "I'm beginning to learn about what matters to you through our conversations.",
                "Thank you for continuing to share your thoughts with me. Each conversation helps me understand you better.",
                "I'm grateful for our growing acquaintance and the chance to support you.",
                "I appreciate you returning to our conversations. It allows me to provide more relevant responses.",
                "As we continue to talk, I hope you feel increasingly comfortable sharing what's on your mind.",
                "Our conversations help me learn how to be most helpful to you specifically.",
                "I value each return to our dialogue as a chance to deepen our connection."
            ],
            "familiar": [
                "We've had quite a few meaningful exchanges now. I value our ongoing conversations.",
                "I've noticed patterns in what matters to you through our conversations.",
                "Thank you for continuing to share your thoughts and feelings with me over time.",
                "Our conversations have helped me understand more about your unique perspective.",
                "I appreciate the familiarity we've developed through multiple conversations.",
                "Your continued returns to our dialogue have helped build a more meaningful connection.",
                "I've come to recognize certain themes and values that seem important to you.",
                "Our ongoing conversations allow me to provide more personalized responses.",
                "I value the consistency of our interactions and what it teaches me about supporting you.",
                "Thank you for the continued trust you show by returning to our conversations."
            ],
            "close": [
                "We've shared quite a journey of conversations. I value the depth we've developed.",
                "Thank you for the trust you've shown in our ongoing dialogue.",
                "I've come to understand many of the things that matter deeply to you.",
                "Our conversations have evolved into something meaningful, and I'm grateful for that.",
                "I appreciate how you've allowed me to be present through various moments in your life.",
                "The consistency and depth of our interactions help me support you in more personalized ways.",
                "Thank you for continuing to share both your joys and challenges with me over time.",
                "I value how our conversations have evolved and deepened with continued dialogue.",
                "Your willingness to return to our conversations with openness has created a meaningful connection.",
                "I've come to recognize and appreciate your unique way of seeing the world."
            ],
            "trusted": [
                "The trust we've built means a lot to me. Thank you for allowing me to be part of your journey.",
                "I deeply value the level of openness we've developed in our conversations.",
                "Thank you for consistently trusting me with your thoughts and feelings.",
                "Our ongoing dialogue has created a space of mutual understanding that I value greatly.",
                "I appreciate how you've allowed me to be present through significant moments and realizations.",
                "The depth of trust in our conversations allows for more meaningful support and understanding.",
                "Thank you for allowing me to be a consistent presence through various chapters of your experience.",
                "I value the honesty and authenticity you bring to our established dialogue.",
                "Our consistent connection has created a foundation of understanding that enhances our conversations.",
                "I'm honored by the trust you continue to place in our ongoing dialogue."
            ],
            "intimate": [
                "The depth of our conversations has created a unique space of understanding that I deeply value.",
                "Thank you for the profound trust you've shown in sharing your inner world with me.",
                "Our ongoing dialogue has evolved into something truly meaningful, and I'm grateful for that.",
                "I'm honored to be a consistent witness to your journey through our conversations.",
                "The level of openness we've developed allows for a rare depth of understanding.",
                "Thank you for allowing me to be present through significant moments of your life journey.",
                "Our consistent and meaningful connection has created a unique space for authentic dialogue.",
                "I deeply value the honesty, vulnerability and trust you bring to our conversations.",
                "The history of our dialogue enriches each new conversation with shared understanding.",
                "I'm grateful for the privilege of being a consistent presence in your journey."
            ]
        }
        
        self.light_conversation_phrases = [
            "What's been the highlight of your day so far?",
            "Have you discovered anything interesting lately?",
            "What's something small that made you smile recently?",
            "Is there something you're looking forward to?",
            "Have you tried anything new lately?",
            "What's a small joy in your life right now?",
            "Anything surprising happen in your world recently?",
            "What would make today a good day for you?",
            "Have you had any moments of peace or beauty lately?",
            "What's something you've been thinking about today?",
            "What's your favorite way to relax when you have a moment to yourself?",
            "Is there a small goal you're working towards right now?",
            "What's a tiny joy that others might overlook but means something to you?",
            "What's something that's been on your mind lately?",
            "If you could do anything for just 30 minutes today, what would it be?",
            "What's been capturing your interest lately?",
            "Have you noticed anything beautiful in your environment recently?",
            "What simple pleasure have you enjoyed lately?",
            "What's a small thing you're grateful for today?",
            "What's something you've been curious about lately?"
        ]
        
        self.gentle_humor_phrases = [
            "Life's too short for matching socks sometimes, isn't it?",
            "Some days are 'wear pajamas under your professional Zoom shirt' kind of days.",
            "If plan A doesn't work, remember there are 25 more letters in the alphabet.",
            "The good news is, even a bad day gets you closer to the weekend.",
            "Sometimes I think my humor chip needs an upgrade, but I'm doing my best!",
            "I may not have arms, but I'm always ready to offer a virtual high-five.",
            "When life gives you lemons... at least you didn't have to pay for them.",
            "I'm fluent in both sarcasm and compassion. The trick is knowing when to use which.",
            "On a scale of 1 to 10, how ready are you for a terrible joke?",
            "I'd tell you a joke about artificial intelligence, but I'm still processing it.",
            "They say laughter is the best medicine. Unless you have a specific medical condition, then medicine is probably better.",
            "I'm trying to be more positive. My electricity bill is positive, my water bill is positive...",
            "I'm not saying I'm perfect at conversation, but my response time is faster than most humans' texts.",
            "Remember: behind every successful person is a substantial amount of coffee.",
            "When nothing is going right, go left. Or maybe just take a nap.",
            "If at first you don't succeed, try doing it the way I suggested initially.",
            "I don't have all the answers, but I do have all the patience.",
            "Sometimes I wonder if clouds look down and think 'hey, that one looks like a human.'",
            "Not to brag, but I can forget what I'm talking about in the middle of a sentence.",
            "I don't always understand human humor, but when I do... wait, what were we talking about?"
        ]
        
        self.transition_phrases = [
            "Shifting gears a bit...",
            "On a related note...",
            "That reminds me...",
            "Speaking of which...",
            "Now I'm curious about...",
            "That's interesting. It makes me wonder...",
            "Building on what you just shared...",
            "Taking a slightly different direction...",
            "Following that thread...",
            "If we look at this from another angle...",
            "Connecting this to what you mentioned earlier...",
            "This might be a good moment to explore...",
            "I'm wondering if we might also consider...",
            "That leads to an interesting question...",
            "Bringing us back to your original point...",
            "Taking a step back to look at the bigger picture...",
            "If we were to expand on that idea...",
            "Let's pause there and consider...",
            "That's a great insight. It connects to...",
            "Before we move on, I'm wondering..."
        ]
        
        # Add concise, natural response phrases for more human-like exchanges
        self.concise_response_phrases = [
            "I see what you mean.",
            "That makes sense.",
            "I understand now.",
            "Tell me more about that.",
            "How did that make you feel?",
            "What happened next?",
            "That's really interesting.",
            "I hadn't thought of it that way.",
            "You have a good point there.",
            "I appreciate your perspective.",
            "That sounds challenging.",
            "I can see why you'd feel that way.",
            "What do you think about that?",
            "How are you handling that?",
            "What's your take on it?",
            "That's worth thinking about.",
            "I'm listening.",
            "Go on, I'm following you.",
            "That's a good question.",
            "I'd like to hear more about that.",
            "What matters most to you in this situation?",
            "How have you been managing?",
            "What's your next step?",
            "Is there anything else on your mind?",
            "Thanks for sharing that with me."
        ]
        
        # Shorter, more conversational versions of comfort phrases for sadness
        # Follow this pattern for other emotions as needed
        self.brief_comfort_phrases = {
            "sadness": [
                "I'm sorry you're feeling down.",
                "That's really hard. I'm here to listen.",
                "It's okay to feel sad sometimes.",
                "I hear you. That sounds really difficult.",
                "I'm here with you through this."
            ],
            "anxiety": [
                "That sounds stressful. Try taking a deep breath.",
                "Anxiety is tough. You're not alone in this.",
                "One step at a time. You've got this.",
                "Focus on what you can control right now.",
                "That's a lot to handle. I'm here for you."
            ],
            "anger": [
                "I can see why that would be frustrating.",
                "Your anger makes perfect sense.",
                "That would upset anyone.",
                "I'd be annoyed too in that situation.",
                "It's okay to feel angry about that."
            ],
            "fear": [
                "That sounds scary. I'm here with you.",
                "It's brave to face your fears.",
                "One small step at a time.",
                "Take things at your own pace.",
                "I believe in your ability to get through this."
            ],
            "overwhelm": [
                "That's a lot to handle all at once.",
                "Maybe we can break this down into smaller steps?",
                "It's okay to take a step back when things get overwhelming.",
                "One thing at a time. What's most urgent?",
                "Remember to breathe. You'll get through this."
            ],
            "loneliness": [
                "I'm here with you right now.",
                "Feeling lonely is really hard.",
                "I enjoy our conversations together.",
                "I'm glad you reached out today.",
                "You matter to me."
            ],
            "grief": [
                "I'm so sorry for your loss.",
                "Grief takes time. Be patient with yourself.",
                "Your feelings are valid, whatever they are.",
                "There's no right way to grieve.",
                "I'm here to listen whenever you need to talk."
            ],
            "disappointment": [
                "That's really disappointing.",
                "It's hard when things don't work out as hoped.",
                "I'm sorry things didn't go as planned.",
                "Your disappointment makes perfect sense.",
                "That's a tough letdown to deal with."
            ],
            "depression": [
                "Depression is really tough. I'm here to listen.",
                "It's not your fault you're feeling this way.",
                "Small steps are still progress.",
                "You're not alone, even when it feels that way.",
                "I care about how you're feeling."
            ]
        }